### ISSUE TITLE
Couldn't normalize path

### ISSUE THREAD

**Issue by bryce-carson** [Toby-exe/react-chart-editoR#1]
```
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'plotly_editor-input-1.0.0'; `directoryPath` = '/home/bryce/R/x86_64-redhat-linux-gnu-library/4.3/reactcharteditor/www/reactcharteditor/plotly_editor'
  6: runApp
  5: print.shiny.appobj
  3: ss
  2: .ess.source
  1: base::as.environment("ESSR")$.ess.eval
```

On my desktop, which hasn't had a local installation of _reactcharteditor_, I encounter this fatal server error when I run Episim.

I think if Ashok was able to install the package from GitHub and then tried to run the application he would have encountered this issue also. I'm unsure.

**Comment by Toby-exe** [comment]
I am unable to recreate this issue even after removing 'reactcharteditor' from my macs library and even getting the expected 
```Bash
Loading required package: reactcharteditor
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘reactcharteditor’
```
for which I reinstalled from 
```Bash
Using GitHub PAT from the git credential store.
Downloading GitHub repo Toby-exe/react-chart-editoR@HEAD
```

**Comment by bryce-carson** [comment]
I'm closing this issue because I'm working on making the package fetch react-chart-editor from jsdelivr rather than building it ourselves and shipping it in the package, so this issue won't be relevant anymore.

It's a stepping stone for using this as a box module in Episim rather than as a package installed from GitHub during runtime (if not already installed on the machine). It'll still be an R package and provide the same functionality, users will simply need to be online.

**Comment by bryce-carson** [comment]
I'm closing this issue because I'm working on making the package fetch react-chart-editor from jsdelivr rather than building it ourselves and shipping it in the package, so this issue won't be relevant anymore.

It's a stepping stone for using this as a box module in Episim rather than as a package installed from GitHub during runtime (if not already installed on the machine). It'll still be an R package and provide the same functionality, users will simply need to be online.
